(function(){
 let panel,file,source,selection,pdf,generation=0,busy=false,host;
 const bridge=()=>window.rafexPdfReadingV201;
 const say=text=>{panel.querySelector('[data-reading-status]').textContent=text;};
 function reset(){generation++;selection=null;panel?.remove();panel=null;file=null;source=null;pdf?.destroy();pdf=null;}
 function paint(){const c=panel.querySelector('canvas'),ctx=c.getContext('2d');c.width=source.width;c.height=source.height;ctx.drawImage(source,0,0);if(selection){ctx.strokeStyle='#008855';ctx.lineWidth=4;ctx.strokeRect(selection.x,selection.y,selection.w,selection.h);}}
 async function renderPage(){const token=++generation;selection=null;panel.querySelector('[data-results]').replaceChildren();panel.querySelector('[data-send]').disabled=true;try{const page=await pdf.getPage(Number(panel.querySelector('[data-page]').value)),v=page.getViewport({scale:1}),scale=Math.min(2,2048/Math.max(v.width,v.height)),viewport=page.getViewport({scale});const c=document.createElement('canvas');c.width=Math.ceil(viewport.width);c.height=Math.ceil(viewport.height);await page.render({canvasContext:c.getContext('2d'),viewport}).promise;if(token!==generation)return;source=c;paint();say('Sayfa hazır. İstersen sürükleyerek yalnız okunacak bölgeyi seç.');panel.querySelector('[data-send]').disabled=false;}catch(e){if(token===generation)say(e.message);}}
 async function open(next,dialog){if(busy)return;reset();file=next;host=dialog;const token=generation;panel=document.createElement('section');panel.id='rafexDocumentAgent';panel.innerHTML='<h3>PDF / Fotoğraf Okuma Agent’ı</h3><p>Okunabilen ölçüleri kontrol için çıkarır; bulanık ayrıntıları uydurmaz. Çizimi otomatik değiştirmez.</p><label data-pages hidden>PDF sayfası <select data-page></select></label><canvas aria-label="Gönderilecek sayfa; sürükleyerek bölge seç"></canvas><button data-full>Tüm sayfa</button><p>Yalnız bu sayfa veya seçtiğiniz bölge ve mevcut OCR metni OpenAI’ye gönderilir. İşlem üst sınırı 0,10 $. Başarısız istek otomatik tekrarlanmaz.</p><button data-send disabled>Seçili sayfa / bölgeyi agent ile oku</button><button data-dismiss>Kapat</button><p data-reading-status aria-live="polite"></p><div data-results></div>';dialog.querySelector('[data-files]').after(panel);
 panel.querySelector('[data-dismiss]').onclick=()=>{if(!busy)reset();};panel.querySelector('[data-full]').onclick=()=>{if(!busy&&source){selection=null;paint();}};panel.querySelector('[data-page]').onchange=()=>{if(!busy)renderPage();};panel.querySelector('[data-send]').onclick=read;
 const canvas=panel.querySelector('canvas');let start;const point=e=>{const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*canvas.height/r.height))};};canvas.onpointerdown=e=>{if(busy||!source)return;start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=e=>{if(!start||busy)return;const end=point(e),w=Math.abs(end.x-start.x),h=Math.abs(end.y-start.y);selection=w>20&&h>20?{x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w,h}:null;start=null;paint();};canvas.onpointercancel=()=>{start=null;};
 say('Önizleme hazırlanıyor…');try{if(next.type==='application/pdf'||/\.pdf$/i.test(next.name)){const lib=await import('/pdfjs/pdf.mjs');lib.GlobalWorkerOptions.workerSrc='/pdfjs/pdf.worker.mjs';const loading=lib.getDocument({data:new Uint8Array(await next.arrayBuffer()),isEvalSupported:false});const documentPdf=await loading.promise;if(token!==generation){documentPdf.destroy();return;}pdf=documentPdf;const select=panel.querySelector('[data-page]');for(let i=1;i<=pdf.numPages;i++){const option=document.createElement('option');option.value=i;option.textContent=String(i);select.append(option);}panel.querySelector('[data-pages]').hidden=false;await renderPage();}else{const bitmap=await createImageBitmap(next);if(token!==generation){bitmap.close();return;}const ratio=Math.min(1,2048/Math.max(bitmap.width,bitmap.height));source=document.createElement('canvas');source.width=Math.round(bitmap.width*ratio);source.height=Math.round(bitmap.height*ratio);source.getContext('2d').drawImage(bitmap,0,0,source.width,source.height);bitmap.close();paint();say('Görsel hazır. İstersen sürükleyerek okunacak bölgeyi seç.');panel.querySelector('[data-send]').disabled=false;}}catch(e){if(token===generation)say('Önizleme açılamadı: '+e.message);}
 }
 async function read(){if(busy||!source||!bridge().contains(file))return;busy=true;const token=generation,project=window.rafexProjectIdentityV133?.uuid;panel.querySelectorAll('button,select').forEach(e=>e.disabled=true);panel.querySelector('[data-results]').replaceChildren();say('Ölçüler okunuyor…');try{const area=selection||{x:0,y:0,w:source.width,h:source.height},c=document.createElement('canvas');c.width=Math.round(area.w);c.height=Math.round(area.h);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(source,area.x,area.y,area.w,area.h,0,0,c.width,c.height);const image=c.toDataURL('image/jpeg',.88);if(image.length>2800000)throw Error('Görsel büyük; daha küçük bir bölge seç.');const response=await fetch('/api/layout-agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'document',requestId:crypto.randomUUID(),prompt:'Görünen raf ölçülerini oku. Belirsiz bilgileri sor.',image,ocr:selection||pdf?'':bridge().ocr(file).slice(0,1200)})});const data=await response.json();if(token!==generation)return;if(!response.ok)throw Error(data.error||'Okuma tamamlanamadı.');if(!host.open||!bridge().contains(file)||project!==window.rafexProjectIdentityV133?.uuid)throw Error('Dosya veya proje değişti; sonuç uygulanmadı.');show(data.plan);say('Okuma tamamlandı. Kaynak görselle karşılaştırıp aktarılacak ölçüleri kendin seç.');}catch(e){if(token===generation)say(e.message);}finally{busy=false;if(token===generation&&panel)panel.querySelectorAll('button,select').forEach(e=>e.disabled=false);}}
 function show(result){const box=panel.querySelector('[data-results]'),summary=document.createElement('p');summary.textContent=result.summary;box.append(summary);const table=document.createElement('table'),selected=[];for(const r of result.readings){const row=document.createElement('tr'),cell=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.disabled=r.confidence!=='high';check.setAttribute('aria-label',r.field+' aktar');cell.append(check);row.append(cell);for(const text of [new Map(bridge().fields()).get(r.field)||r.field,String(r.value),r.evidence+(r.confidence==='uncertain'?' — BELİRSİZ':'')]){const td=document.createElement('td');td.textContent=text;row.append(td);}selected.push({check,r});table.append(row);}box.append(table);for(const note of [...result.notes,...result.questions]){const p=document.createElement('p');p.textContent=note;box.append(p);}const button=document.createElement('button');button.textContent='Seçtiğim ölçüleri kontrol formuna aktar';button.onclick=()=>{try{if(!bridge().contains(file))throw Error('Dosya kaldırıldı.');const values=selected.filter(x=>x.check.checked&&!x.check.disabled).map(x=>x.r);if(!values.length)throw Error('Önce doğruladığın ölçüleri seç.');bridge().apply(file,values);say('Seçilen ölçüler forma aktarıldı. Yerleşim uygulanmadı; ölçü ve göz kontrolünü tamamla.');}catch(e){say(e.message);}};box.append(button);}
 window.rafexDocumentAgentV201={open};
 function install(){const dialog=document.getElementById('rafexPdfAutoDialog');if(!dialog)return;const input=dialog.querySelector('[data-file]');if(input)input.accept='application/pdf,image/png,image/jpeg,.pdf,.png,.jpg,.jpeg';const header=dialog.querySelector('h2');if(header&&header.textContent!=='PDF / Fotoğraf Okuma ve Yerleşim')header.textContent='PDF / Fotoğraf Okuma ve Yerleşim';dialog.querySelectorAll('[data-files] > p').forEach((row,index)=>{if(row.querySelector('[data-read-file]'))return;const button=document.createElement('button');button.dataset.readFile=index;button.textContent='Agent ile oku';row.append(button);});if(!dialog.dataset.readingBound){dialog.dataset.readingBound='1';dialog.addEventListener('close',reset);}}
 new MutationObserver(install).observe(document.body,{childList:true,subtree:true});install();
})();
