(function(){
 let panel,file,source,selection,pdf,generation=0,busy=false,host,rotation=0,zoom=100,pageObject,renderScale=1;
 const reviews=new WeakMap();
 function review(){const project=window.rafexProjectIdentityV133?.uuid;let state=reviews.get(file);if(!state||state.project!==project){state={project,questions:[],answers:{},result:null,turns:[]};reviews.set(file,state);}return state;}
 function continuation(){const state=review();return state.questions.map(q=>({question:q,answer:(state.answers[q]||'').trim()}));}
 const bridge=()=>window.rafexPdfReadingV201;
 const say=text=>{panel.querySelector('[data-reading-status]').textContent=text;const local=panel.querySelector('[data-followup-status]');if(local)local.textContent=text;};
 function readingContext(){const state=review();return JSON.stringify({page:Number(panel.querySelector('[data-page]').value||1),rotation,region:selection?{x:selection.x/source.width,y:selection.y/source.height,w:selection.w/source.width,h:selection.h/source.height}:null,summary:state.result?.summary?.slice(0,800)||'',answers:continuation(),messages:state.turns.map(t=>({request:t.request,reply:t.reply.slice(0,300),page:t.page,region:t.region})),pendingQuestions:state.questions.slice(0,2)});}
 function reset(){generation++;rotation=0;zoom=100;pageObject=null;selection=null;panel?.remove();panel=null;file=null;source=null;pdf?.destroy();pdf=null;}
 function paint(){const c=panel.querySelector('canvas'),ctx=c.getContext('2d');c.width=source.width;c.height=source.height;ctx.drawImage(source,0,0);c.style.cssText='max-width:none;width:'+zoom+'%;height:auto';if(selection){ctx.strokeStyle='#008855';ctx.lineWidth=4;ctx.strokeRect(selection.x,selection.y,selection.w,selection.h);}}
 async function renderPage(){const token=++generation;selection=null;panel.querySelector('[data-results]').replaceChildren();panel.querySelector('[data-send]').disabled=true;try{const page=await pdf.getPage(Number(panel.querySelector('[data-page]').value)),v=page.getViewport({scale:1,rotation:(page.rotate+rotation)%360}),scale=1800/Math.max(v.width,v.height),viewport=page.getViewport({scale,rotation:(page.rotate+rotation)%360});const c=document.createElement('canvas');c.width=Math.ceil(viewport.width);c.height=Math.ceil(viewport.height);await page.render({canvasContext:c.getContext('2d'),viewport}).promise;if(token!==generation)return;pageObject=page;renderScale=scale;source=c;paint();selectionLabel();say('Sayfa hazır. İstersen sürükleyerek yalnız okunacak bölgeyi seç.');panel.querySelector('[data-send]').disabled=false;}catch(e){if(token===generation)say(e.message);}}
 async function open(next,dialog){if(busy)return;reset();file=next;host=dialog;const token=generation;panel=document.createElement('section');panel.id='rafexDocumentAgent';panel.innerHTML='<h3>PDF / Fotoğraf Okuma Agent’ı</h3><p>Okunabilen ölçüleri kontrol için çıkarır; bulanık ayrıntıları uydurmaz. Çizimi otomatik değiştirmez.</p><label data-pages hidden>PDF sayfası <select data-page></select></label><div style="display:flex;flex-wrap:wrap;gap:6px"><button data-rotate>90° döndür</button><button data-zoom-out>−</button><span data-zoom>100%</span><button data-zoom-in>+</button><button data-expand>Geniş görünüm</button></div><div data-viewport style="overflow:auto;max-height:65vh;border:1px solid #bdd6c8"><canvas aria-label="Gönderilecek sayfa; sürükleyerek bölge seç"></canvas></div><p data-selection>Kaynak: tüm sayfa. Bölgeyi sürükleyerek işaretleyebilirsiniz.</p><button data-full>Tüm sayfa</button><p>Yalnız bu sayfa veya seçtiğiniz bölge ve mevcut OCR metni OpenAI’ye gönderilir. İşlem üst sınırı 0,10 $. Başarısız istek otomatik tekrarlanmaz.</p><label>Agent’a isteğini yaz<textarea data-question maxlength="1000" rows="3" style="width:100%;box-sizing:border-box" placeholder="Örneğin: İşaretlediğim bölgedeki tünelli rafları açıkla."></textarea></label><small>Her gönderimde yalnız seçili sayfa/bölge ve son konuşmanın sınırlı metni iletilir. Diğer sayfalar otomatik görülmez.</small><details><summary>Bu dosyadaki konuşma</summary><div data-conversation></div></details><button data-send disabled>Seçili sayfa / bölgeyi agent ile oku</button><button data-dismiss>Kapat</button><p data-reading-status aria-live="polite"></p><div data-results></div>';dialog.querySelector('[data-files]').after(panel);
 panel.querySelector('[data-dismiss]').onclick=()=>{if(!busy)reset();};panel.querySelector('[data-full]').onclick=()=>{if(!busy&&source){selection=null;paint();selectionLabel();}};panel.querySelector('[data-page]').onchange=()=>{if(!busy)renderPage();};panel.querySelector('[data-send]').onclick=read;
 panel.querySelector('[data-rotate]').onclick=()=>{if(!busy&&pdf){rotation=(rotation+90)%360;renderPage();}};
 panel.querySelector('[data-zoom-in]').onclick=()=>changeZoom(25);panel.querySelector('[data-zoom-out]').onclick=()=>changeZoom(-25);panel.querySelector('[data-expand]').onclick=()=>{const wide=host.dataset.agentWide!=='1';host.dataset.agentWide=wide?'1':'0';host.style.width=wide?'min(1400px,96vw)':'';};
 const history=panel.querySelector('[data-conversation]');history.parentElement.open=true;history.setAttribute('role','log');history.setAttribute('aria-label','Dosya hakkında konuşma');history.style.cssText='max-height:320px;overflow:auto';history.parentElement.querySelector('summary').textContent='Dosya hakkında konuşalım';
 const composer=panel.querySelector('[data-question]');composer.placeholder='Cevabını veya düzeltmeni yaz. Örn: Opt.1; ayak 6400 mm, üst palet kotu 6500 mm, ayak arası 200 mm.';composer.parentElement.firstChild.textContent='Mesajın';
 const send=panel.querySelector('[data-send]');send.textContent='Gönder · en fazla 0,10 $';panel.append(composer.parentElement,send);composer.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();read();}});
 for(const turn of review().turns)appendTurn(turn);
 const canvas=panel.querySelector('canvas');let start;const point=e=>{const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*canvas.width/r.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*canvas.height/r.height))};};canvas.onpointerdown=e=>{if(busy||!source)return;start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=e=>{if(!start||busy)return;const end=point(e),w=Math.abs(end.x-start.x),h=Math.abs(end.y-start.y);selection=w>20&&h>20?{x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w,h}:null;start=null;paint();selectionLabel();};canvas.onpointercancel=()=>{start=null;};
 panel.querySelector('[data-rotate]').disabled=!(/\.pdf$/i.test(next.name)||next.type==='application/pdf');
 say('Önizleme hazırlanıyor…');try{if(next.type==='application/pdf'||/\.pdf$/i.test(next.name)){const lib=await import('/pdfjs/pdf.mjs');lib.GlobalWorkerOptions.workerSrc='/pdfjs/pdf.worker.mjs';const loading=lib.getDocument({data:new Uint8Array(await next.arrayBuffer()),isEvalSupported:false});const documentPdf=await loading.promise;if(token!==generation){documentPdf.destroy();return;}pdf=documentPdf;const select=panel.querySelector('[data-page]');for(let i=1;i<=pdf.numPages;i++){const option=document.createElement('option');option.value=i;option.textContent=String(i);select.append(option);}panel.querySelector('[data-pages]').hidden=false;await renderPage();}else{const bitmap=await createImageBitmap(next);if(token!==generation){bitmap.close();return;}const ratio=Math.min(1,2048/Math.max(bitmap.width,bitmap.height));source=document.createElement('canvas');source.width=Math.round(bitmap.width*ratio);source.height=Math.round(bitmap.height*ratio);source.getContext('2d').drawImage(bitmap,0,0,source.width,source.height);bitmap.close();paint();say('Görsel hazır. İstersen sürükleyerek okunacak bölgeyi seç.');panel.querySelector('[data-send]').disabled=false;}}catch(e){if(token===generation)say('Önizleme açılamadı: '+e.message);}
 }

 function changeZoom(delta){if(busy||!source)return;zoom=Math.max(50,Math.min(400,zoom+delta));panel.querySelector('[data-zoom]').textContent=zoom+'%';paint();}
 function selectionLabel(){panel.querySelector('[data-selection]').textContent='Sayfa '+(panel.querySelector('[data-page]').value||1)+' · '+(selection?'İşaretli bölge':'Tüm sayfa')+' · Döndürme '+rotation+'°';}
 function appendTurn(turn){const log=panel.querySelector('[data-conversation]');for(const [who,text] of [['Siz',turn.request],['Agent',turn.reply]]){const p=document.createElement('p');p.style.cssText='white-space:pre-wrap;padding:10px;border-radius:8px;background:'+(who==='Siz'?'#edf4ff':'#f0f7f3');p.textContent=who+': '+text;log.append(p);}log.scrollTop=log.scrollHeight;}
 async function imageForReading(){
  const area=selection||{x:0,y:0,w:source.width,h:source.height},c=document.createElement('canvas'),factor=2048/Math.max(area.w,area.h);
  c.width=Math.max(1,Math.round(area.w*factor));c.height=Math.max(1,Math.round(area.h*factor));
  const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);
  if(pdf&&pageObject){const viewport=pageObject.getViewport({scale:renderScale*factor,rotation:(pageObject.rotate+rotation)%360});await pageObject.render({canvasContext:ctx,viewport,transform:[1,0,0,1,-area.x*factor,-area.y*factor]}).promise;}
  else{const bitmap=await createImageBitmap(file);try{const sx=bitmap.width/source.width,sy=bitmap.height/source.height;ctx.drawImage(bitmap,area.x*sx,area.y*sy,area.w*sx,area.h*sy,0,0,c.width,c.height);}finally{bitmap.close();}}
  return c.toDataURL('image/jpeg',.88);
 }

 async function read(){if(busy||!source||!bridge().contains(file))return;if(readingContext().length>6000){say('Konuşma işlem bütçesinin bağlam sınırına ulaştı. Önceki cevaplar korunuyor; hiçbir istek gönderilmedi.');return;}busy=true;const token=generation,project=window.rafexProjectIdentityV133?.uuid;panel.querySelectorAll('button,select,textarea').forEach(e=>e.disabled=true);say('Ölçüler okunuyor…');try{const prompt=panel.querySelector('[data-question]').value.trim()||'Görünen raf ölçülerini oku. Belirsiz bilgileri sor.';const image=await imageForReading();if(token!==generation)return;if(image.length>2800000)throw Error('Görsel büyük; daha küçük bir bölge seç.');const response=await fetch('/api/layout-agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'document',requestId:crypto.randomUUID(),prompt,context:readingContext(),image,ocr:selection||pdf?'':bridge().ocr(file).slice(0,1200)})});const data=await response.json();if(token!==generation)return;if(!response.ok)throw Error(data.error||'Okuma tamamlanamadı.');if(!host.open||!bridge().contains(file)||project!==window.rafexProjectIdentityV133?.uuid)throw Error('Dosya veya proje değişti; sonuç uygulanmadı.');const turn={request:prompt,reply:data.plan.summary,page:Number(panel.querySelector('[data-page]').value||1),region:selection?'Seçili bölge':'Tüm sayfa'};review().turns.push(turn);appendTurn(turn);panel.querySelector('[data-question]').value='';review().result=data.plan;review().questions=data.plan.questions;show(data.plan);say('Okuma tamamlandı. Kaynak görselle karşılaştırıp aktarılacak ölçüleri kendin seç.');}catch(e){if(token===generation)say(e.message);}finally{busy=false;if(token===generation&&panel)panel.querySelectorAll('button,select,textarea').forEach(e=>e.disabled=false);}}
 function show(result){const box=panel.querySelector('[data-results]');box.replaceChildren();const summary=document.createElement('p');summary.style.whiteSpace='pre-wrap';summary.textContent=result.summary;box.append(summary);const table=document.createElement('table'),selected=[];for(const r of result.readings){const row=document.createElement('tr'),cell=document.createElement('td'),check=document.createElement('input');check.type='checkbox';check.disabled=r.confidence!=='high';check.setAttribute('aria-label',r.field+' aktar');cell.append(check);row.append(cell);for(const text of [new Map(bridge().fields()).get(r.field)||r.field,String(r.value),r.evidence+(r.confidence==='uncertain'?' — BELİRSİZ':'')]){const td=document.createElement('td');td.textContent=text;row.append(td);}selected.push({check,r});table.append(row);}box.append(table);for(const note of result.notes){const p=document.createElement('p');p.textContent=note;box.append(p);}const button=document.createElement('button');button.textContent='Seçtiğim ölçüleri kontrol formuna aktar';button.onclick=()=>{try{if(!bridge().contains(file))throw Error('Dosya kaldırıldı.');const values=selected.filter(x=>x.check.checked&&!x.check.disabled).map(x=>x.r);if(!values.length)throw Error('Önce doğruladığın ölçüleri seç.');bridge().apply(file,values);say('Seçilen ölçüler forma aktarıldı. Yerleşim uygulanmadı; ölçü ve göz kontrolünü tamamla.');}catch(e){say(e.message);}};box.append(button);
 const section=document.createElement('section'), heading=document.createElement('h4');heading.textContent=result.questions.length?'Devam etmek için':'Kontrol için hazır · nihai uygunluk onayı değildir';section.append(heading);
 for(const question of result.questions.slice(0,2)){const p=document.createElement('p');p.textContent=question;section.append(p);}
 if(result.questions.length){const hint=document.createElement('small');hint.textContent='Aşağıdaki mesaj kutusundan cevap verebilir, düzeltme yapabilir veya bilmediğini söyleyebilirsin. Bütün soruları doldurmak zorunda değilsin.';section.append(hint);}
 const status=document.createElement('p');status.dataset.followupStatus='';status.setAttribute('role','status');status.setAttribute('aria-live','polite');section.append(status);box.append(section);
 }
 window.rafexDocumentAgentV201={open};
 function install(){const dialog=document.getElementById('rafexPdfAutoDialog');if(!dialog)return;const input=dialog.querySelector('[data-file]');if(input)input.accept='application/pdf,image/png,image/jpeg,.pdf,.png,.jpg,.jpeg';const header=dialog.querySelector('h2');if(header&&header.textContent!=='PDF / Fotoğraf Okuma ve Yerleşim')header.textContent='PDF / Fotoğraf Okuma ve Yerleşim';dialog.querySelectorAll('[data-files] > p').forEach((row,index)=>{if(row.querySelector('[data-read-file]'))return;const button=document.createElement('button');button.dataset.readFile=index;button.textContent='Agent ile oku';row.append(button);});if(!dialog.dataset.readingBound){dialog.dataset.readingBound='1';dialog.addEventListener('close',reset);}}
 new MutationObserver(install).observe(document.body,{childList:true,subtree:true});install();
})();
