#!/usr/bin/env bash
set -euo pipefail

node scripts/patch-mekik-common-latest-context-v1.mjs
node scripts/patch-mekik-viewer-stability-v1.mjs
node scripts/patch-mekik-front-glb-v2.mjs
node scripts/patch-common-mekik-front-glb-v1.mjs
node scripts/patch-remove-legacy-mekik-front-runtime-v1.mjs
node scripts/patch-common-system-isolation-v1.mjs
node scripts/patch-common-mekik-view-colors-v1.mjs
node scripts/patch-heavy-viewers-on-demand-v1.mjs
node scripts/patch-uniform-system-banner-v95.mjs
node scripts/patch-common-layout-theme-v96.mjs
node scripts/patch-runtime-authority-v2.mjs
node scripts/patch-module-access-common-v98.mjs
node scripts/patch-common-b2b-input-card-v100.mjs
node scripts/patch-common-mekik-input-card-v101.mjs
node scripts/patch-b2b-3d-save-height-v103.mjs
node scripts/patch-uniform-color-controls-v1.mjs
node scripts/patch-uniform-common-picker-height-v1.mjs
node scripts/patch-sidebar-order-v100.mjs
node scripts/patch-free-drag-distance-v104.mjs
node scripts/verify-runtime-authority-v2.mjs
node scripts/verify-common-runtime-cleanup-v109.mjs
node scripts/verify-b2b-collection-products-v110.mjs
node scripts/patch-dist-version-badge-position-v1.mjs
node scripts/verify-inventory-systems-v112.mjs
node scripts/verify-uniform-system-banner-v95.mjs
node scripts/patch-b2b-collection-behavior-v109.mjs
node scripts/patch-common-system-previews-v115.mjs
node scripts/verify-common-system-previews-v115.mjs
node scripts/verify-b2b-detail-source-v134.mjs
node scripts/verify-b2b-levels-v121.mjs
node scripts/verify-unified-rack-registry-v116.mjs
node scripts/patch-common-layout-zoom-crisp-v126.mjs
node scripts/verify-common-layout-zoom-crisp-v126.mjs
node scripts/verify-common-layout-physical-scale-v127.mjs
node scripts/patch-pdf-upright-visibility-v129.mjs
node scripts/verify-pdf-upright-visibility-v129.mjs
node scripts/patch-independent-performance-v133.mjs
node scripts/patch-layout-performance-v135.mjs
node scripts/verify-layout-runtime-v135.mjs
node scripts/verify-independent-project-v133.mjs
node scripts/verify-delete-saved-types.mjs
node scripts/verify-api-proxy.mjs
node scripts/patch-rack-detail-snapshot-v135.mjs
node scripts/verify-rack-detail-snapshot-v135.mjs
node scripts/patch-plan-annotations-v136.mjs
node scripts/verify-plan-annotations-v136.mjs
node scripts/patch-screen-session-v136.mjs
node scripts/patch-common-konsol-controls-v137.mjs
node scripts/patch-common-wall-fit-v138.mjs
node scripts/patch-common-zoom-header-v139.mjs
node scripts/patch-pdf-layout-margin-v140.mjs
node scripts/patch-pdf-tight-fit-v141.mjs
node scripts/patch-pdf-page-ruler-v142.mjs
node scripts/verify-screen-runtime-v136.mjs
node scripts/patch-plan-detail-v143.mjs
node scripts/verify-plan-detail-v143.mjs
node scripts/patch-type-colors-v144.mjs
node scripts/verify-type-colors-v144.mjs
node scripts/patch-shared-feet-performance-v146.mjs
node scripts/verify-shared-feet-runtime-v146.mjs
node scripts/patch-idle-dom-performance-v147.mjs
node scripts/patch-static-selection-v148.mjs
node scripts/verify-rack-gap-search-v148.mjs
node scripts/patch-static-deselection-v149.mjs
node scripts/patch-plan-toolbar-v150.mjs
node scripts/patch-b2b-accessory-floor-levels-v151.mjs
node scripts/verify-travers-calculator.mjs
node scripts/verify-rack-travers-selection.mjs
node scripts/verify-travers-injection.mjs
node scripts/patch-travers-calculator.mjs
node scripts/patch-shared-camera-panel.mjs
node scripts/patch-tray-calculator.mjs
node scripts/verify-tray-calculator.mjs
node scripts/patch-common-ui.mjs
node scripts/patch-plan-snapshot.mjs
node scripts/patch-section-print.mjs
node scripts/verify-konsol-workbook.mjs
node scripts/verify-konsol-levels.mjs
node scripts/verify-konsol-render-budget.mjs
node scripts/verify-konsol-plan-products.mjs
node scripts/patch-konsol-workbook.mjs
node scripts/patch-stable-rack-catalog.mjs
node scripts/patch-dimension-drag.mjs
node scripts/patch-all-section-systems.mjs
node scripts/verify-all-section-systems.mjs
node scripts/patch-multi-area.mjs
node scripts/patch-section-identity.mjs
node scripts/verify-section-identity.mjs
node scripts/patch-native-technical-sections.mjs
node scripts/verify-native-technical-sections.mjs
node scripts/verify-multi-area.mjs
node scripts/verify-mr-custom-detail.mjs
node scripts/verify-dimension-drag.mjs
node scripts/verify-stable-rack-catalog.mjs dist/server/index.js
node scripts/verify-common-performance.mjs dist/server/index.js
node scripts/build-shared-three.mjs
node scripts/patch-free-selection-v145.mjs
node scripts/verify-free-selection-v145.mjs
node scripts/patch-common-workflow-screens.mjs
node scripts/patch-layout-budget-v152.mjs
node scripts/verify-layout-budget-v152.mjs
node scripts/patch-drag-isolation-v153.mjs
node scripts/verify-drag-isolation-v153.mjs
node scripts/patch-distance-labels-v154.mjs
node scripts/patch-project-catalog-v155.mjs
node scripts/patch-project-records-v156.mjs
node scripts/patch-project-start-v157.mjs
node scripts/patch-drawing-catalog-v158.mjs
node scripts/patch-rack-label-v160.mjs
node scripts/patch-common-ui-v161.mjs
node scripts/patch-mekik-summary-v162.mjs
node scripts/patch-layout-accessories-v165.mjs
node scripts/patch-customize-performance-v166.mjs
node scripts/patch-layout-pan-v168.mjs
node scripts/patch-barrier-center-v169.mjs
node scripts/patch-project-isolation-v170.mjs
node scripts/patch-seismic-style-v172.mjs
node scripts/patch-repeat-tool-v173.mjs
node scripts/patch-seismic-center-v174.mjs
node scripts/patch-mixed-join-v176.mjs
node scripts/patch-customize-ui-v178.mjs
node scripts/patch-regions-repeat-v179.mjs
node scripts/patch-audit-fixes-v184.mjs
node scripts/patch-mixed-layout-v186.mjs
node scripts/patch-b2b-default-clearance-v187.mjs
node scripts/patch-pdf-auto-layout-v188.mjs
node scripts/patch-free-area-preserve-v189.mjs
node scripts/patch-layout-agent-v188.mjs
node scripts/patch-customize-save-v203.mjs
node scripts/patch-column-collision-v204.mjs
node scripts/patch-wallless-workspace-v205.mjs
node scripts/patch-pallet-clean-v206.mjs
node scripts/patch-pallet-palette-v207.mjs
node scripts/patch-top-palette-v208.mjs
node scripts/patch-opening-perf-v209.mjs
node scripts/patch-lane-contour-v210.mjs
node scripts/patch-b2b-contour-v211.mjs
node scripts/patch-common-perf-v212.mjs
node scripts/patch-mr-speed-v213.mjs
node scripts/patch-floating-tools-v214.mjs
node scripts/patch-seismic-color-v215.mjs
node scripts/patch-tool-menus-v216.mjs
node scripts/patch-selection-menu-v217.mjs
node scripts/patch-sidebar-auto-v218.mjs
node scripts/patch-center-menus-v219.mjs
node scripts/patch-canvas-height-v220.mjs
node scripts/patch-ruler-extension-v221.mjs
node scripts/patch-shortcuts-v222.mjs
node scripts/patch-pointer-canvas-v223.mjs
node scripts/patch-add-rack-menu-v224.mjs
node scripts/patch-wall-guides-v225.mjs
node scripts/patch-shortcut-b2b-v226.mjs
node scripts/patch-area-width-v227.mjs
node scripts/patch-actual-walls-v228.mjs
node scripts/patch-unit-status-v229.mjs
node scripts/patch-bulk-output-v230.mjs
node scripts/patch-no-auto-rack-v231.mjs
node scripts/patch-site-localization-v202.mjs
node scripts/emit-static-index-v1.mjs
node scripts/verify-idle-dom-runtime-v147.mjs dist/index.html
node scripts/verify-viewer-visibility-v147.mjs
node scripts/split-runtime-assets-v152.mjs
